### ISSUE TITLE
Beta 1.3 crash

### ISSUE THREAD

**Issue by Andrelol221** [Designer225/CustomTroopUpgrades#7]
![image](https://user-images.githubusercontent.com/64378405/80318063-e3f18580-87dd-11ea-8451-d4bafaed12df.png)

**Comment by Designer225** [comment]
Huh. Seems like TaleWorlds removed that convenient function. I'll temporarily update my game to beta branch to check it out.

**Comment by Designer225** [comment]
So it turns out TaleWorlds didn't remove that function, but moved MBObjectManager into a separate DLL. I'll see if I can make the mod compatible with e1.3 without having to break compatibility with e1.2. If not, I'll push an update once e1.3 is stable.

**Comment by Designer225** [comment]
I got good news and bad news.

Bad news is that TaleWorlds' move meant that the e1.2 version cannot be updated to work with the e1.3 version. This unfortunately means that a separate version will have to be compiled to e1.3.

The good news is that it's about the only issue that I am aware of. I'll release a pre-release version for e1.3 when I wake up in the morning (it's 12:39 AM PT here). Since I don't use beta though, I'll need you guys to provide feedback. (Don't worry, the pre-release will be up on the nexus.)

**Comment by Designer225** [comment]
Released a release candidate. I need all the feedback I can get as I don't play on betas...

**Comment by Andrelol221** [comment]
Very quick work man, it seems to be fixed now, i did'nt had any crash, great work man!

**Comment by Designer225** [comment]
Dev test complete. Merging update and closing issue.
